/* Administrator prototype layer. Keeps mock tasks separate from presentation. */
(function(){
 const store=window.AdminDemoRepository;
 const previousContent=content,previousNav=workspaceNav,previousRender=render,previousReset=repo.reset;
 let adminSessionActive=false,view='list';
 const routes=new Set(['admin','admin-system','admin-content','admin-talent','admin-surveys','admin-plans','admin-camps']);
 const menu=[
  ['管理概況',[['admin','工作區首頁']]],
  ['網站管理',[['admin-system','系統與權限'],['admin-content','網站內容'],['admin-talent','人才資料庫']]],
  ['業務作業',[['admin-surveys','調查表管理'],['admin-plans','計畫審查'],['admin-camps','營隊活動管理']]],
  ['共用',[['home','公開網站'],['guide','展示說明']]]
 ];
 const pending=()=>store.pending();
 const taskTime=task=>task.kind==='deadline'?`截止：${esc(task.due)}`:`收到：${esc(task.received)} · 未設定截止時間`;
 function nav(){return menu.map(([group,items])=>`<div class="workspace-group"><h2>${group}</h2>${items.map(([id,label])=>{const count=pending().filter(task=>task.route===id).length;return `<button data-page="${id}" class="admin-nav-link ${page===id?'active':''}" ${page===id?'aria-current="page"':''}><span>${label}</span>${count?`<span class="admin-nav-count" aria-label="${count} 件未完成">${count}</span>`:''}</button>`;}).join('')}</div>`).join('');}
 function taskCard(task){return `<li class="admin-task"><div><strong>${esc(task.title)}</strong><small>${taskTime(task)}</small><p>${esc(task.detail)}</p></div><button data-admin-go="${esc(task.route)}">前往處理</button></li>`;}
 function taskList(tasks,empty){return tasks.length?`<ul class="admin-task-list">${tasks.map(taskCard).join('')}</ul>`:`<p class="admin-empty">${empty}</p>`;}
 function summary(){const tasks=pending();return `<dialog id="admin-summary" aria-labelledby="admin-summary-title"><div class="admin-summary-head"><div><h2 id="admin-summary-title">待處理事項（${tasks.length}）</h2><p>展開可看內容；開啟分頁不會清除提醒。</p></div><button id="admin-close-summary" type="button" aria-label="關閉待處理摘要">關閉</button></div>${tasks.length?tasks.map(task=>`<details class="admin-summary-item"><summary><strong>${esc(task.title)}</strong><small>${taskTime(task)}</small></summary><p>${esc(task.detail)}</p><button type="button" class="primary" data-admin-go="${esc(task.route)}">前往處理</button></details>`).join(''):'<p class="admin-empty">目前沒有未完成事項。</p>'}<p class="admin-summary-note">此處皆為假資料；只有完成示範處理後，左側件數才會清除。</p></dialog>`;}
 function calendar(){const all=store.all().filter(task=>task.kind==='deadline'),first=new Date(2026,9,1).getDay();const cells=[];for(let i=0;i<first;i++)cells.push('<span class="admin-calendar-blank"></span>');for(let day=1;day<=31;day++){const tasks=all.filter(task=>Number(task.due.slice(8,10))===day);cells.push(`<div class="admin-calendar-day"><span class="admin-calendar-date">${day}</span>${tasks.map(task=>`<button data-admin-go="${esc(task.route)}" class="${task.done?'done':''}" title="${esc(task.title)}">${esc(task.title)}${task.done?'（已完成）':''}</button>`).join('')}</div>`);}return `<section class="card admin-calendar-wrap"><div class="admin-calendar-caption"><h2>2026 年 10 月作業期限</h2><span>只顯示有日期的事項</span></div><div class="admin-calendar-scroll"><div class="admin-calendar">${['日','一','二','三','四','五','六'].map(d=>`<strong>${d}</strong>`).join('')}${cells.join('')}</div></div></section>`;}
 function dashboard(){const tasks=pending(),deadlines=tasks.filter(t=>t.kind==='deadline'),requests=tasks.filter(t=>t.kind==='request'),v=store.visitors();return heading('ADMINISTRATION','管理工作台','示範今日：2026/10/02 · 待辦與網站資訊皆為假資料')+`<div class="admin-dash-intro"><p><strong>${tasks.length} 件待處理</strong> · 閱讀摘要或進入分頁後仍會保留提醒，完成示範處理才清除。</p><button id="admin-open-summary" type="button">查看待處理摘要</button></div><section class="admin-stats" aria-label="瀏覽人數示例">${[['當前',v.current],['本日',v.day],['本月',v.month],['本年',v.year]].map(([label,value])=>`<div class="card"><span>${label}瀏覽人數</span><strong>${value.toLocaleString('zh-TW')}</strong></div>`).join('')}</section><p class="admin-demo-caption">瀏覽數字為固定展示值，未串接統計服務；計數口徑待團隊確認。</p><div class="admin-view-switch" role="group" aria-label="期限檢視方式"><button data-admin-view="list" aria-pressed="${view==='list'}" class="${view==='list'?'active':''}">文字清單</button><button data-admin-view="calendar" aria-pressed="${view==='calendar'}" class="${view==='calendar'?'active':''}">日曆檢視</button></div>${view==='list'?`<section class="card admin-list-section"><h2>近期到期／今日待辦</h2><p>只有設定了截止時間的作業列在這裡。</p>${taskList(deadlines,'目前沒有未完成的期限事項。')}</section>`:calendar()}<section class="card admin-list-section"><h2>收到的待處理申請</h2><p>依收到時間列出；未設定截止時間的申請不放進日曆。</p>${taskList(requests,'目前沒有未完成的申請。')}</section>${summary()}`;}
 function taskPage(title,desc,route,body){const tasks=store.all().filter(task=>task.route===route);return heading('ADMINISTRATION',title,desc)+`<p class="note warning">管理員操作示例：資料只在本次展示記憶體中變動，未連接正式權限或審查 API。</p><section class="card admin-list-section"><h2>本頁事項</h2>${tasks.length?tasks.map(task=>`<div class="admin-work-item"><div><strong>${esc(task.title)}</strong><small>${taskTime(task)}</small><p>${esc(task.detail)}</p><span class="badge ${task.done?'green':'orange'}">${task.done?'已完成示範處理':'尚未完成'}</span></div>${task.done?'':`<button class="primary" data-admin-complete="${esc(task.id)}">完成示範處理</button>`}</div>`).join(''):'<p>目前沒有本頁待處理的示範事項。</p>'}</section>${body}`;}
 function adminPage(){switch(page){
  case 'admin':return dashboard();
  case 'admin-system':return taskPage('系統與權限','學校資料、帳號與承辦權限的示範入口。','admin-system','<section class="card admin-extra"><h2>角色範例</h2><p>示範國小 A：一般學校；示範國小 B：一般學校＋承辦。上方申請是獨立假資料，完成示範處理不會修改這兩個登入角色。</p></section>');
  case 'admin-content':return taskPage('網站內容','公告、輪播、檔案與公開資訊的管理入口示例。','admin-content','<section class="card admin-extra"><h2>網站內容項目</h2><p>首頁輪播、最新消息、FAQ、檔案下載與好站連結依需求書設置。此版只展示待辦導流，內容編輯仍待管理員角色頁面整合。</p></section>');
  case 'admin-talent':return taskPage('人才資料庫','類別與對外公開欄位的管理入口示例。','admin-talent','<section class="card admin-extra"><h2>公開欄位</h2><p>姓名、服務單位、職稱、專長、照片等欄位是否公開，正式系統由管理員設定；此版沒有修改真實資料。</p></section>');
  case 'admin-surveys':return taskPage('調查表管理','填報期間與未填報學校的示範入口。','admin-surveys','<section class="card admin-extra"><h2>調查進度</h2><p>示範調查表的截止日顯示在工作區日曆；正式系統仍須提供新增題目、指定學校、查未填報及匯出。</p></section>');
  case 'admin-plans':return taskPage('計畫審查','收到的計畫申請示範入口。','admin-plans','<section class="card admin-extra"><h2>兩階段審查</h2><p>正式審查有第一、第二階段及意見欄；本頁只示範收到申請後的待辦流轉，不產生正式審查結果。</p></section>');
  case 'admin-camps':return taskPage('營隊活動管理','活動與梯次設定的示範入口。','admin-camps','<section class="card admin-extra"><h2>營隊資料</h2><p>訪客營隊頁使用預建活動資料；管理員設定、匯出與活動結束後刪除紀錄尚待實作。</p><button data-page="camp">查看訪客營隊頁</button></section>');
 }}
 workspaceNav=function(){return role==='admin'?nav():previousNav();};
 content=function(a){return role==='admin'&&routes.has(page)?adminPage():previousContent(a);};
 repo.reset=function(){previousReset.call(repo);store.reset();view='list';adminSessionActive=false;};
 function bindAdmin(){document.querySelector('#admin-open-summary')?.addEventListener('click',()=>document.querySelector('#admin-summary')?.showModal());document.querySelector('#admin-close-summary')?.addEventListener('click',()=>document.querySelector('#admin-summary')?.close());document.querySelectorAll('[data-admin-go]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#admin-summary')?.close();navigate(button.dataset.adminGo);}));document.querySelectorAll('[data-admin-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.adminView;render();}));document.querySelectorAll('[data-admin-complete]').forEach(button=>button.addEventListener('click',()=>{store.complete(button.dataset.adminComplete);render();notify('示範處理已完成，未完成件數已更新。');}));}
 render=function(){const entering=role==='admin'&&!adminSessionActive;if(role!=='admin')adminSessionActive=false;previousRender();if(role==='admin'){bindAdmin();if(entering){adminSessionActive=true;const dialog=document.querySelector('#admin-summary');dialog?.showModal();dialog?.querySelector('#admin-close-summary')?.focus();}}};
 // A refreshed administrator URL cannot restore a simulated login session.
 if(/^#admin(?:-|$)/.test(location.hash)&&role!=='admin')navigate('login');
})();
