const repo=window.DemoRepository;
let role='visitor',page='home',resultTab='order';
const roles={visitor:'訪客｜公開網站',school:'一般學校｜示範國小 A',host:'承辦學校｜示範國小 B',admin:'系統管理員'};
const statusText={pending:'待審核',revision:'待補件',approved:'審核通過'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modules=[['survey','線上調查填報','指定學校填報，掌握回收進度與統計。'],['resource','教學資源與成果','集中整理教材、活動成果與分享資源。'],['plan','計畫與經費填報','計畫申請、經費概算與兩階段審查。'],['camp','營隊活動','公開場次、免登入報名與正備取管理。']];
function button(label,action,cls=''){return `<button class="${cls}" data-action="${action}">${label}</button>`;}
function badge(status){return `<span class="badge ${status==='approved'?'green':status==='revision'?'orange':'blue'}">${statusText[status]||esc(status)}</span>`;}
function notify(text){const t=document.querySelector('#toast');t.textContent=text;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',3000);}
function navigate(p){if(p==='home')role='visitor';page=p;history.replaceState(null,'','#'+p);render();window.scrollTo(0,0);}
function heading(kicker,title,desc){return `<div class="title-row"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p class="muted">${desc}</p></div></div>`;}
function render(){
document.querySelector('#toast').style.display='none';
const a=repo.get().application;
document.body.className=role==='visitor'?'public':'workspace';
document.querySelector('#app').innerHTML=`<div class="demo"><span><strong>原型展示</strong>　非正式網站 · 所有活動與人物均為示範資料</span><details class="demo-tools"><summary>展示工具</summary><div><label for="role">切換示範身分</label><select id="role">${Object.entries(roles).map(([k,v])=>`<option value="${k}" ${role===k?'selected':''}>${v}</option>`).join('')}</select>${button('重設展示','reset','small')}<button data-page="guide">展示說明</button></div></details></div><div class="shell"><aside><div class="brand"><span class="mark">E</span><div><b>臺中市<br>英語教育資源中心</b><small>ENGLISH RESOURCE CENTER</small></div></div><div class="nav-label">服務與工作區</div><nav>${workspaceNav()}</nav><div class="side-foot"><b>讓學習資源連結每一所學校</b><br>課程資源 · 活動參與 · 行政協作<br><br>離線原型 v1.0</div></aside><div>${role==='visitor'?publicHeader():`<header><div><strong>${role==='host'?'示範國小 B｜學校工作區':role==='admin'?'系統管理工作區':'學校工作區'}</strong><div class="role-hint">${role==='host'?'承辦權限已開啟，同時保留一般學校功能':role==='admin'?'待辦、網站內容與權限管理':'學校作業與案件進度'}</div></div><div><button data-page="home">公開網站</button> ${button('登出示範身分','logout','small')}</div></header>`}<main id="main">${content(a)}${role==='visitor'?publicFooter():'<footer>臺中市英語教育資源中心｜工作區原型 · 未串接正式服務</footer>'}</main></div></div><dialog id="reset-dialog"><h2>重設展示資料？</h2><p>將清除本次模擬案件與公告，回到最初的展示狀態。</p><div class="actions">${button('取消','cancel-reset')}${button('確認重設','confirm-reset','primary')}</div></dialog>`;
document.querySelector('#role').addEventListener('change',e=>{role=e.target.value;page=role==='visitor'?'home':role==='host'?'host-home':role==='admin'?'admin':'application';render();});
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));
if(typeof bindPublic==='function')bindPublic();
if(typeof bindOrganizer==='function')bindOrganizer();
const form=document.querySelector('#registration');if(form)form.addEventListener('input',()=>{document.querySelector('#error').textContent='';});if(form)form.addEventListener('submit',e=>{e.preventDefault();try{repo.submit(Object.fromEntries(new FormData(form)));render();notify('報名已送出，等待承辦學校審核。');}catch(err){document.querySelector('#error').textContent=err.message;}});
}
function coreContent(a){
if(page==='home')return `<section class="hero"><div><div class="eyebrow">TAICHUNG · ENGLISH EDUCATION</div><h1>Hello, world!<br>一起探索英語的世界。</h1><p class="muted">從教學資源到競賽活動，讓學校參與、承辦審核與成果分享，在同一個平台完成。</p>${button('參加英語競賽','competition')} <button data-page="resource">找教學資源</button></div><div class="hero-art"><img src="learning.png" alt="老師與孩子一起閱讀，探索英語學習的樂趣"></div></section><div class="grid"><div class="card"><div class="eyebrow">PARTICIPATE</div><h2>學校參與</h2><p>填報、報名與補件，集中追蹤每一件申請。</p>${button('進入學校工作區','school','small')}</div><div class="card"><div class="eyebrow">COLLABORATE</div><h2>承辦協作</h2><p>審核文件、確認名冊，掌握活動辦理進度。</p>${button('進入承辦工作區','host','small')}</div><div class="card"><div class="eyebrow">SHARE</div><h2>公開成果</h2><p>查看出場順序與競賽公告，分享學習成果。</p>${button('查看成果公告','results','small')}</div></div><div class="section-head"><h2>今天想做什麼？</h2><span class="muted">依用途找到需要的服務</span></div><div class="grid">${moduleCards()}</div><div class="section-head"><h2>最新消息</h2><span class="badge">範例內容</span></div><div class="card"><div class="flow-row"><b>競賽活動</b>　英語朗讀競賽開放學校線上報名</div><div class="flow-row"><b>資源分享</b>　英語教學活動設計與成果交流</div></div>`;
if(page==='competition')return heading('COMPETITION','英語朗讀競賽','整合報名、文件審核與成果公告。')+`<div class="two"><section class="card"><span class="badge green">報名開放中 · 模擬時段</span><h2 style="margin-top:20px">讓每一次參與，都有清楚的進度。</h2><p>參賽學校填寫資料並附上報名文件。承辦學校將檢視文件；若需補件，學校可查看意見並重新送出。</p><div class="meta"><div><small>活動組別</small>國小朗讀組</div><div><small>承辦學校</small>示範國小 B</div><div><small>辦理地點</small>示範活動中心</div><div><small>本次展示</small>一校一筆案件</div></div>${role==='visitor'?button('以一般學校身分報名','school','primary'):'<button data-page="application" class="primary">前往本校競賽案件</button>'}</section><section class="card"><h2>參與流程</h2><div class="flow-row">01　填寫資料與附上文件</div><div class="flow-row">02　承辦審核與補件</div><div class="flow-row">03　確認資格與名冊</div><div class="flow-row">04　抽籤、登分與公告</div><p class="muted" style="margin-top:20px">本頁活動及規則均為展示資料。</p></section></div>`;
if(page==='application')return application(a);
if(typeof organizerPage==='function'&&organizerRoutes.includes(page))return organizerPage(a);
if(page==='review')return review(a);
if(page==='results')return results();
if(page==='guide')return guide();
if(page==='admin')return heading('ADMINISTRATION','管理工作台','配置服務與權限，支援全市學校協作。')+`<div class="note warning">設定示意：下列內容為預建資料，本版不執行真實帳號授權或網站設定。</div><div class="grid"><section class="card"><div class="number">01</div><h2>帳號與承辦權限</h2><p>示範國小 A：一般學校<br>示範國小 B：一般學校＋承辦</p><span class="badge">競賽歸屬規則待確認</span></section><section class="card"><div class="number">02</div><h2>競賽報名欄位</h2><p>學校、組別、參賽者、指導教師、報名附件。</p><span class="badge">展示欄位，非最終規格</span></section><section class="card"><div class="number">03</div><h2>網站內容管理</h2><p>中心資訊、消息、輪播、人才資料庫與公開欄位。</p><span class="badge">範例畫面</span></section>${moduleCards()}</div>`;
const m=modules.find(m=>m[0]===page);if(m)return modulePage(m);
return '';
}
function moduleCards(){return modules.map(([id,title,desc],i)=>`<button class="card link" data-page="${id}"><span class="number">0${i+1}</span><h3>${title}</h3><p>${desc}</p><span class="badge">範例畫面</span></button>`).join('');}
function application(a){
let out=heading('SCHOOL WORKSPACE','我的競賽案件','示範國小 A · 英語朗讀競賽');
if(role==='host')return heading('SCHOOL SERVICES','本校報名／補件','示範國小 B · 學校作業')+`<div class="note">同一帳號可直接使用左側「學校作業」及「競賽承辦」，不需切換工作區或重新登入。</div><section class="card empty"><h2>本校尚無參賽案件</h2><p>此頁為本校案件空狀態示例。可操作的跨校報名案例使用示範國小 A；承辦審核則查看所承辦競賽的報名資料。</p><span class="badge">本校報名表尚未擴充至多校案例</span></section>`;
if(role!=='school')return out+`<section class="card empty"><h2>請先切換學校身分</h2>${button('進入一般學校','school','primary')}</section>`;
if(!a)return out+`<div class="steps"><div class="step current">01 填寫報名</div><div class="step">02 文件審核</div><div class="step">03 必要時補件</div><div class="step">04 審核通過</div></div><div class="two"><section class="card"><h2>參賽資料</h2><form id="registration" novalidate><div class="form-grid"><label class="field">學校<input value="示範國小 A" readonly></label><label class="field">參賽組別<select name="group"><option>國小朗讀組</option></select></label><label class="field">參賽者姓名（必填）<input name="student" maxlength="30" placeholder="例如：示範學生" required></label><label class="field">指導教師（必填）<input name="teacher" maxlength="30" placeholder="例如：示範老師" required></label></div><label class="field">報名文件（必選）<select name="attachment" required><option value="">請選擇示範附件</option><option>報名暨授權書_示範.pdf</option></select></label><p class="muted">僅模擬附件名稱，不讀取或上傳真實檔案。</p><div id="error" class="error" role="alert"></div><button type="submit" class="primary">送出報名</button></form></section><section class="card"><h2>送出前確認</h2><p>填寫姓名及指導教師，並選擇示範報名文件。</p><div class="note">送出後切換「承辦學校」，即可審核這一筆案件。</div><h3>本版展示假設</h3><p>報名時段開放、名額足夠、校別與組別符合。一校一筆案例，尚未涵蓋正式名額與時窗規則。</p></section></div>`;
return out+caseDetail(a,false);
}
function caseDetail(a,isReview){return `<div class="steps">${['填寫報名','文件審核','必要時補件','審核通過'].map((x,i)=>`<div class="step ${i===(a.status==='approved'?3:a.status==='revision'?2:1)?'current':i===0?'done':''}">0${i+1} ${x}</div>`).join('')}</div><div class="two"><section class="card"><div class="title-row"><div><div class="eyebrow">${a.id}</div><h2 style="margin:5px 0">英語朗讀競賽 · ${esc(a.school)}</h2></div>${badge(a.status)}</div><div class="meta"><div><small>參賽者</small>${esc(a.student)}</div><div><small>指導教師</small>${esc(a.teacher)}</div><div><small>參賽組別</small>${esc(a.group)}</div><div><small>目前附件（模擬）</small>${esc(a.attachment)}</div></div>${a.comment?`<div class="note ${a.status==='revision'?'warning':''}"><strong>最近一次審核意見</strong><br>${esc(a.comment)}</div>`:''}${isReview?(a.status==='pending'?`<label class="field">審核意見（要求補件時必填）<textarea id="comment" maxlength="500" placeholder="例如：請補上授權書簽名頁。"></textarea></label><div id="error" class="error" role="alert"></div><div class="actions">${button('要求補件','revision')}${button('核准報名','approve','primary')}</div>`:`<div class="note">${a.status==='revision'?'已標記待補件，學校可在案件頁查看意見，重新送出後再審核。':'此案件已通過，可列入參賽名冊。'}</div>`):(a.status==='revision'?`<label class="field">補件文件<select id="revision-file"><option value="">請選擇新的示範附件</option><option>授權書_簽名完成_示範.pdf</option></select></label><div id="error" class="error" role="alert"></div>${button('重新送出補件','resubmit','primary')}`:`<div class="note">${a.status==='pending'?'案件已送出，等待承辦學校審核。':'報名審核通過，請留意後續出場序公告。'}</div>`)}<div class="actions">${button(isReview?'切到學校查看進度':'切到承辦審核',isReview?'school':'host','small')}${a.status==='approved'?button('查看後續展示情境','results','small'):''}</div></section><section class="card"><h2>案件歷程</h2><ul class="history">${a.history.slice().reverse().map(h=>`<li><time>${esc(h.time)}</time>${esc(h.text)}</li>`).join('')}</ul><span class="badge">跨角色共用同一筆案件</span></section></div>`;}
function review(a){let out=heading('ORGANIZER WORKSPACE','競賽審核工作台','示範國小 B · 承辦英語朗讀競賽');if(role!=='host')return out+`<div class="card">${button('切換承辦學校','host','primary')}</div>`;return out+`<div class="grid" style="margin-bottom:22px"><div class="card"><span class="muted">待審核</span><div class="stat">${a?.status==='pending'?1:0}</div></div><div class="card"><span class="muted">待補件</span><div class="stat">${a?.status==='revision'?1:0}</div></div><div class="card"><span class="muted">已通過</span><div class="stat">${a?.status==='approved'?1:0}</div></div></div>`+(a?caseDetail(a,true):`<section class="card empty"><h2>目前沒有待審案件</h2><p>先由一般學校送出報名，再回到這裡審核。</p>${button('切到一般學校填寫報名','school','primary')}</section>`);}
function results(){const published=repo.get().results;return heading('COMPETITION RESULTS','出場序與成果公告','英語朗讀競賽 · 後續流程展示')+`<div class="note warning">預建情境：此處三所學校、出場序與名次為獨立範例，不由剛才的報名案件產生；尚未實作抽籤或計分算法。</div>${role==='host'?`<div class="tabs">${button('出場序示例','tab-order',resultTab==='order'?'active':'')}${button('成績與公告示例','tab-score',resultTab==='score'?'active':'')}</div>`:''}<section class="card"><div class="title-row"><h2>${role==='host'&&resultTab==='order'?'出場序預覽':'競賽成果'}</h2><span class="badge ${published?'green':'orange'}">${published?'已發布示範公告':'示範公告尚未發布'}</span></div>${role==='host'||published?`<div class="table-wrap"><table><thead><tr><th>出場序</th><th>學校</th><th>組別</th>${resultTab==='score'||role!=='host'?'<th>獎項</th>':''}</tr></thead><tbody>${[['01','示範國小 C','第一名'],['02','示範國小 D','第二名'],['03','示範國小 E','佳作']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>國小朗讀組</td>${resultTab==='score'||role!=='host'?`<td>${r[2]}</td>`:''}</tr>`).join('')}</tbody></table></div><p class="muted" style="margin-top:18px">公開示例僅顯示學校、組別、出場序及獎項，不包含學生姓名或審核意見。</p>`:`<div class="empty"><h3>目前尚無公開成果</h3><p>請由承辦學校發布示範公告後，再切回訪客查看。</p></div>`}${role==='host'?`<div class="actions">${published?'<span class="badge green">已完成發布</span>':button('發布示範公告','publish','primary')}${button('以訪客查看','public-results')}</div>`:button('切到承辦展示發布','host-results','small')}</section>`;}
function modulePage(m){const examples={survey:['英語教學需求調查','填報對象：受指定學校','學校填寫 → 欄位檢查 → 管理員統計','本年度英語教學資源需求','數位教材、教學研習、活動支援'],resource:['教學活動與成果分享','使用對象：學校、管理員與訪客','學校上傳 → 格式檢查 → 依公開設定展示','英語繪本共讀活動','教材、文字說明、成果照片'],plan:['英語推廣計畫','使用對象：學校與管理員','計畫與概算 → 第一階段審查 → 第二階段審查','校園英語閱讀推廣','計畫書、經費概算、附件'],camp:['英語探索營','使用對象：訪客與管理員','選擇場次 → 填寫報名 → 正備取結果','英語故事體驗營','活動場次、報名期間、名額資訊']};const e=examples[m[0]];return heading('SERVICE PREVIEW',m[1],m[2])+`<div class="note warning">範例畫面 · 本次未實作送出、上傳、審查或名額計算。</div><div class="two"><section class="card"><div class="number">${m[0]==='camp'?'04':m[0]==='plan'?'03':m[0]==='resource'?'02':'01'}</div><h2>${e[0]}</h2><p>${e[1]}</p><div class="flow-row"><small class="muted">範例主題</small><h3>${e[3]}</h3></div><div class="flow-row"><small class="muted">預計提供</small><p>${e[4]}</p></div></section><section class="card"><h2>預計操作流程</h2><p>${e[2]}</p><h3>實作前需確認</h3><p>${m[0]==='camp'?'重複報名判斷、正備取與資料保留方式。':m[0]==='plan'?'退回修正、再次送審與兩階段狀態轉換。':m[0]==='resource'?'檔案限制、分類欄位與對外公開規則。':'欄位型態、期限與送出後能否修改。'}</p>${button('回到可操作的競賽流程','competition','primary')}</section></div>`;}
function guide(){return heading('DEMO GUIDE','用一筆案件，說清楚整個流程','現場操作約 3–5 分鐘；資料只保留於目前頁面，重新整理即重設。')+`<div class="two"><section class="card"><h2>建議展示順序</h2>${['首頁：介紹整合入口與服務範圍','一般學校：故意漏填，展示驗證，再送出報名','承辦學校：填寫意見並要求補件','一般學校：查看意見、選擇補件文件並送出','承辦學校：核准，確認同一案件的歷程','後續情境：預建出場序、成績與公告','訪客：查看公告；最後按重設可再演一次'].map((t,i)=>`<div class="flow-row"><b>0${i+1}</b>${t}</div>`).join('')}</section><section class="card"><h2>範圍與限制</h2><h3>已確認</h3><p>四種使用身分、承辦保留學校功能、競賽跨角色協作、離線展示。</p><h3>展示假設</h3><p>一校一筆案例、報名時段開放、名額足夠、預先指定承辦；補件不設截止時間。</p><h3>仍待確認</h3><p>名額計算、三段時窗、補件期限、計分公式、授權歸屬及各模組正式欄位。</p><h3>兩週後整合目標</h3><p>正式登入、資料庫與 API、伺服器驗證及實際文件處理。本版尚未完成這些功能。</p></section></div>`;}
function action(id){try{
if(id==='logout'){role='visitor';return navigate('home');}
if(['home','competition','results'].includes(id))return navigate(id);
if(id==='school'||id==='host'){role=id;return navigate(id==='school'?'application':'host-home');}
if(id==='host-results'){role='host';return navigate('results');}
if(id==='public-results'){role='visitor';return navigate('results');}
if(id==='reset')return document.querySelector('#reset-dialog').showModal();
if(id==='cancel-reset')return document.querySelector('#reset-dialog').close();
if(id==='confirm-reset'){repo.reset();role='visitor';page='home';resultTab='order';history.replaceState(null,'','#home');render();return notify('展示已重設。');}
if(id==='revision'||id==='approve'){if(role!=='host')throw Error('請使用承辦身分。');repo.review(id==='revision'?'revision':'approved',document.querySelector('#comment').value.trim());render();return notify(id==='revision'?'已要求補件，請切換學校查看。':'報名審核通過。');}
if(id==='resubmit'){if(role!=='school')throw Error('請使用一般學校身分。');repo.resubmit(document.querySelector('#revision-file').value);render();return notify('補件已重新送出。');}
if(id.startsWith('tab-')){resultTab=id.slice(4);return render();}
if(id==='publish'){if(role!=='host')throw Error('請使用承辦身分。');repo.publish();render();return notify('示範成果已公開。');}
}catch(err){const target=document.querySelector('#error');if(target)target.textContent=err.message;else notify(err.message);}}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_demo_status',description:'Read the current fictional application status and demo publication state; no real student data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({status:repo.get().application?.status||'none',published:repo.get().results})})).catch(()=>{});}catch{}}
