(function(){
const store=window.CampRepository, priorContent=content, priorBind=bindPublic, priorReset=repo.reset;
let drafts={},receipt=null,preview=null,busy=false;
const date=s=>s.replace('T',' ').replace(/:00\+08:00$/,'');
const notice='<p class="note">營隊操作原型：請只填假資料。模擬日期固定為 2026/10/01 15:00；重新整理會清除報名。下列日期、學校、名額與欄位皆為展示設定。</p>';
const status=r=>r.status==='regular'?'正取':'備取（尚未錄取）';
function info(e,s){return `<dl class="camp-info"><dt>適合年級</dt><dd>${e.grades.join('、')}</dd><dt>活動日期</dt><dd>${esc(s.dates)}</dd><dt>活動時間</dt><dd>${esc(s.hours)}</dd><dt>地點</dt><dd>${esc(e.location)}</dd><dt>費用</dt><dd>${esc(e.fee)}</dd><dt>報名期間</dt><dd>${date(s.start||e.start)} 至 ${date(s.end||e.end)}</dd></dl>`;}
function eventState(e){const states=e.sessions.map(s=>store.availability(s.id));return states.some(a=>a.canApply&&a.regular)?'開放報名':states.some(a=>a.canApply)?'開放備取':states.some(a=>a.open)?'已額滿':states.some(a=>a.label==='尚未開放')?'尚未開放':'報名已截止';}
function list(){return `<div class="camp-list-heading"><h1>營隊活動</h1><p>先看日期、年級與地點，找到孩子有興趣的活動。</p></div><p class="camp-demo-note">操作原型・以下為示範活動，請勿填寫真實資料。</p><div class="camp-list">${store.events().map(e=>{const dates=[...new Set(e.sessions.map(s=>s.dates.split('（')[0]))].sort();const ends=[...new Set(e.sessions.map(s=>s.end||e.end))].sort();return `<article class="card camp-event"><div class="camp-card-top"><span>${esc(e.type)}</span><span class="badge">${eventState(e)}</span></div><h2><a href="#camp-event/${e.id}">${esc(e.title)}</a></h2><p class="camp-teaser">${esc(e.content)}</p><dl class="camp-compare"><dt>對象</dt><dd>${esc(e.grades[0])}～${esc(e.grades.at(-1))}</dd><dt>日期</dt><dd>${dates.map(esc).join('<br>')}</dd><dt>地點</dt><dd>${esc(e.location)}</dd><dt>費用</dt><dd>${esc(e.fee)}</dd><dt>截止</dt><dd>${date(ends.at(-1))}${ends.length>1?'（各梯次不同）':''}</dd></dl><a class="camp-detail-link" href="#camp-event/${e.id}">查看活動・${e.sessions.length} 個梯次 →</a></article>`;}).join('')}</div>`;}
function eventDetail(id){const e=store.events().find(e=>e.id===id);if(!e)return '<h1>找不到活動</h1><button data-page="camp">返回活動列表</button>';return `<button data-page="camp">返回活動列表</button><div class="camp-list-heading"><h1>${esc(e.title)}</h1><p>${esc(e.type)} · ${esc(e.grades.join('、'))}</p></div>${notice}<article class="card"><h2>活動內容</h2><p>${esc(e.content)}</p><p>地點：${esc(e.location)}<br>費用：${esc(e.fee)}</p><h3>接送安排</h3><p>${esc(e.pickup)}</p><h2>選擇梯次</h2>${e.sessions.map(s=>{const a=store.availability(s.id);return `<section class="camp-session camp-session-choice"><div><h3>${esc(s.name)}</h3><p>${esc(s.dates)} · ${esc(s.hours)}</p><p>報名：${date(s.start||e.start)} 至 ${date(s.end||e.end)}</p><p><strong>${a.label}</strong> · 正取剩餘 ${a.regular} 名 · 備取剩餘 ${a.waiting} 名</p></div><button data-page="camp/${s.id}" class="${a.canApply?'primary':''}">${a.canApply?'選擇此梯次':'查看梯次詳情'}</button></section>`;}).join('')}</article>`;}
function field(key,label,type='text'){return `<label class="field">${label} <span>（必填）</span><input name="${key}" type="${type}" maxlength="${key==='phone'?24:80}" required value="${esc(drafts[previewSession]?.[key]||'')}"></label>`;}
let previewSession='';
function detail(id){let pair;try{pair=store.find(id)}catch{return '<div class="card"><h1>找不到此梯次</h1><button data-page="camp">返回營隊列表</button></div>';}
const {event:e,session:s}=pair,a=store.availability(id);previewSession=id;
const d=drafts[id]||{};
return heading('CAMP DETAILS',`${e.title}｜${s.name}`,`${e.type} · ${a.label}`)+notice+`<button data-page="camp">返回營隊列表</button><div class="two" style="margin-top:20px"><article class="card"><h2>活動詳情</h2>${info(e,s)}<h3>活動內容</h3><p>${e.content}</p><h3>接送安排</h3><p>${e.pickup}</p><h3>注意事項</h3><p>請確認能參加本梯次所有日期。備取不等於錄取；遞補與取消規則尚待團隊確認。本原型不處理付款、住宿或發送通知。</p><p>正取剩餘 ${a.regular} 名 · 備取剩餘 ${a.waiting} 名</p></article><section class="card"><h2>我要報名</h2>${!a.canApply?`<p class="note warning">${a.label}，目前不能報名。仍可查看活動詳情。</p>`:''}<form id="camp-form" data-session="${id}"><fieldset ${a.canApply?'':'disabled'}><legend>孩子資料與聯絡資料</legend>${field('child','孩子姓名')}<label class="field">就讀學校（必填）<select name="schoolId" required><option value="">請選擇學校</option>${store.schools().map(s=>`<option value="${s.id}" ${d.schoolId===s.id?'selected':''}>${s.name}</option>`).join('')}</select></label>${field('studentId','學號')}<p class="muted">請填寫孩子學號（保留開頭的 0）；若不清楚，請先向就讀學校確認。</p><label class="field">年級（必填）<select name="grade" required><option value="">請選擇年級</option>${e.grades.map(g=>`<option ${d.grade===g?'selected':''}>${g}</option>`).join('')}</select></label>${field('contact','家長／聯絡人姓名')}${field('phone','聯絡電話','tel')}${e.extras.length?'<h3>本活動額外資料</h3><p class="muted">以下欄位依管理員設定呈現（本版以設定檔模擬）。</p>':''}${e.extras.map(f=>`<label class="field">${f.label}（${f.required?'必填':'選填'}）<select name="${f.id}" ${f.required?'required':''}><option value="">請選擇</option>${f.options.map(o=>`<option ${d[f.id]===o?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`).join('')}<p>同一梯次以「學校＋學號」判重；預覽不保留名額，以確認送出時為準。</p><div id="camp-error" role="alert" class="error"></div><button type="submit" class="primary">預覽報名資料</button></fieldset></form></section></div><dialog id="camp-preview" aria-labelledby="camp-preview-title"><h2 id="camp-preview-title">確認營隊報名資料</h2><div id="camp-preview-body"></div><div id="camp-preview-error" class="error" role="alert"></div><div class="actions"><button id="camp-back" type="button">返回修改</button><button id="camp-confirm" type="button" class="primary">確定送出</button></div></dialog>`;
}
function summary(r,includePrivate){const {event:e,session:s}=store.find(r.sessionId);const d=r.data;return `<h3>${e.title}｜${s.name}</h3>${info(e,s)}<dl class="camp-info"><dt>孩子姓名</dt><dd>${esc(d.child)}</dd><dt>學校／年級</dt><dd>${esc(store.schools().find(x=>x.id===d.schoolId)?.name)} · ${esc(d.grade)}</dd>${includePrivate?`<dt>學號</dt><dd>${esc(d.studentId)}</dd><dt>聯絡人</dt><dd>${esc(d.contact)}</dd><dt>電話</dt><dd>${esc(d.phone)}</dd>${e.extras.map(f=>`<dt>${f.label}</dt><dd>${esc(d[f.id]||'未填')}</dd>`).join('')}`:''}</dl>`;}
function result(){if(!receipt)return '<section class="card"><h1>目前沒有可顯示的報名摘要</h1><p>本頁不是線上查詢；請在送出成功時儲存摘要。</p><button data-page="camp">返回活動列表</button></section>';return heading('REGISTRATION COMPLETE','模擬報名已完成','請保存報名編號與摘要；本版不提供線上報名查詢。')+`<section class="card" id="camp-receipt"><p>前端模擬摘要 · 非正式報名憑證</p><h2>報名編號：${receipt.id}</h2><p class="badge green">${status(receipt)}</p>${summary(receipt,false)}<p>接送：${store.find(receipt.sessionId).event.pickup}</p>${receipt.status==='waiting'?'<p><strong>目前為備取，尚未錄取，請勿視為已取得參加資格。</strong></p>':''}<p>請保存本摘要。重新整理或重設後無法從此原型查回。</p></section><div class="actions"><button id="camp-print" class="primary">列印／另存 PDF 摘要</button><button data-page="camp">返回營隊列表</button></div>`;}
content=function(a){if(role==='visitor'){if(page==='camp')return list();if(page==='camp-complete')return result();if(page.startsWith('camp-event/'))return eventDetail(page.slice(11));if(page.startsWith('camp/'))return detail(page.slice(5));}return priorContent(a);};
bindPublic=function(){priorBind();const form=document.querySelector('#camp-form');if(form){const id=form.dataset.session;form.addEventListener('input',()=>{drafts[id]=Object.fromEntries(new FormData(form));});form.addEventListener('change',()=>{drafts[id]=Object.fromEntries(new FormData(form));});form.addEventListener('submit',ev=>{ev.preventDefault();drafts[id]=Object.fromEntries(new FormData(form));try{const data=store.validate(id,drafts[id]);preview={sessionId:id,data,token:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),epoch:store.epoch()};document.querySelector('#camp-error').textContent='';document.querySelector('#camp-preview-body').innerHTML=summary(preview,true)+'<p>確認時重新檢查名額；正取額滿時可能改為備取。</p>';document.querySelector('#camp-preview-error').textContent='';document.querySelector('#camp-preview').showModal();document.querySelector('#camp-back').focus();}catch(e){document.querySelector('#camp-error').textContent=e.message;}});
document.querySelector('#camp-back').onclick=()=>{document.querySelector('#camp-preview').close();form.querySelector('[type=submit]').focus();};
document.querySelector('#camp-confirm').onclick=()=>{if(busy||!preview)return;busy=true;const b=document.querySelector('#camp-confirm');b.disabled=true;try{receipt=store.submit(preview.sessionId,preview.data,preview.token,preview.epoch);delete drafts[id];document.querySelector('#camp-preview').close();preview=null;navigate('camp-complete');notify('模擬送出完成：'+status(receipt));}catch(e){document.querySelector('#camp-preview-error').textContent=e.message;b.disabled=false;}finally{busy=false;}};}
document.querySelector('#camp-print')?.addEventListener('click',()=>{document.body.classList.add('printing-camp');window.print();});};
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-camp'));
repo.reset=function(){priorReset.call(repo);store.reset();drafts={};receipt=null;preview=null;busy=false;document.body.classList.remove('printing-camp');language='zh';newsFilter='全部';searchTerm='';resourceTerm='';slide=0;};
function routeCamp(){const h=location.hash.slice(1);if(h==='camp-complete'||h.startsWith('camp/')||h.startsWith('camp-event/')){role='visitor';page=h;render();window.scrollTo(0,0);}}
window.addEventListener('hashchange',routeCamp);routeCamp();render();
})();
