const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'admin-data.js'),'utf8'),context);
const repo=context.window.AdminDemoRepository;
assert.equal(repo.pending().length,4);
assert.equal(repo.pending().filter(t=>t.kind==='deadline').length,2);
assert.equal(repo.pending().filter(t=>t.kind==='request').length,2);
const snapshot=repo.all();
snapshot[0].title='外部讀取不應修改資料';
assert.notEqual(repo.all()[0].title,snapshot[0].title);
assert.equal(repo.pending().length,4,'閱讀待辦不等於完成');
repo.complete('role-request');
assert.equal(repo.pending().length,3);
assert.equal(repo.all().find(t=>t.id==='role-request').done,true);
repo.complete('role-request');
assert.equal(repo.pending().length,3,'重複標記完成不重複扣件數');
assert.throws(()=>repo.complete('unknown'),/找不到/);
repo.reset();
assert.equal(repo.pending().length,4,'重設恢復示範待辦');
assert.deepEqual(Object.keys(repo.visitors()).sort(),['current','day','month','year']);
console.log('PASS: pending vs read, separate deadline/request, complete once, reset, visitor metrics.');
